In [1]:
import pickle

ref_data = [{} for i in range(8)]
total_nums = [0,0,100,0,0,96525,45540,990]

for i in range(5, 8):
    file_path = f'../assets/db/bckt{i}-2.pkl'
    with open(file_path, 'rb') as fp:
        ref_data[i] = pickle.load(fp)

In [21]:
ref_data[2] = {
    '22': 4, '33': 5, '44': 5, '55': 6, '66': 6, '77': 7, '88': 7, '99': 8, 'TT': 9, 'JJ': 9, 'QQ': 10, 'KK': 10, 'AA': 10,
    '23': 1, '24': 1, '25': 1, '26': 1, '27': 1, '28': 2, '29': 2, '2T': 2, '2J': 3, '2Q': 3, '2K': 4, '2A': 5,
    '34': 1, '35': 1, '36': 1, '37': 1, '38': 2, '39': 2, '3T': 3, '3J': 3, '3Q': 4, '3K': 4, '3A': 5,
    '45': 2, '46': 2, '47': 2, '48': 2, '49': 2, '4T': 3, '4J': 3, '4Q': 4, '4K': 4, '4A': 5,
    '56': 2, '57': 2, '58': 2, '59': 3, '5T': 3, '5J': 3, '5Q': 4, '5K': 5, '5A': 6,
    '67': 3, '68': 3, '69': 3, '6T': 3, '6J': 4, '6Q': 4, '6K': 5, '6A': 5,
    '78': 3, '79': 3, '7T': 4, '7J': 4, '7Q': 4, '7K': 5, '7A': 6,
    '89': 4, '8T': 4, '8J': 4, '8Q': 5, '8K': 5, '8A': 6,
    '9T': 4, '9J': 5, '9Q': 5, '9K': 5, '9A': 6,
    'TJ': 5, 'TQ': 5, 'TK': 6, 'TA': 6,
    'JQ': 5, 'JK': 6, 'JA': 7,
    'QK': 6, 'QA': 7,
    'KA': 7, 
    '2s3s': 1, '2s4s': 2, '2s5s': 2, '2s6s': 2, '2s7s': 2, '2s8s': 2, '2s9s': 3, '2sTs': 3, '2sJs': 4, '2sQs': 4, '2sKs': 5, '2sAs': 5,
    '3s4s': 2, '3s5s': 2, '3s6s': 2, '3s7s': 2, '3s8s': 2, '3s9s': 3, '3sTs': 3, '3sJs': 4, '3sQs': 4, '3sKs': 5, '3sAs': 6,
    '4s5s': 2, '4s6s': 2, '4s7s': 3, '4s8s': 3, '4s9s': 3, '4sTs': 3, '4sJs': 4, '4sQs': 4, '4sKs': 5, '4sAs': 6,
    '5s6s': 3, '5s7s': 3, '5s8s': 3, '5s9s': 3, '5sTs': 3, '5sJs': 4, '5sQs': 5, '5sKs': 5, '5sAs': 6, 
    '6s7s': 3, '6s8s': 3, '6s9s': 4, '6sTs': 4, '6sJs': 4, '6sQs': 5, '6sKs': 5, '6sAs': 6,
    '7s8s': 4, '7s9s': 4, '7sTs': 4, '7sJs': 4, '7sQs': 5, '7sKs': 5, '7sAs': 6,
    '8s9s': 4, '8sTs': 4, '8sJs': 5, '8sQs': 5, '8sKs': 6, '8sAs': 6,
    '9sTs': 5, '9sJs': 5, '9sQs': 5, '9sKs': 6, '9sAs': 6,
    'TsJs': 5, 'TsQs': 6, 'TsKs': 6, 'TsAs': 7,
    'JsQs': 6, 'JsKs': 6, 'JsAs': 7,
    'QsKs': 6, 'QsAs': 7,
    'KsAs': 7
}
value_to_char = {1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G', 8: 'H', 9: 'I', 10: 'J'}
for key, value in ref_data[2].items():
        if value in value_to_char:
                ref_data[2][key] = value_to_char[value]
print(ref_data[2])

{'22': 'D', '33': 'E', '44': 'E', '55': 'F', '66': 'F', '77': 'G', '88': 'G', '99': 'H', 'TT': 'I', 'JJ': 'I', 'QQ': 'J', 'KK': 'J', 'AA': 'J', '23': 'A', '24': 'A', '25': 'A', '26': 'A', '27': 'A', '28': 'B', '29': 'B', '2T': 'B', '2J': 'C', '2Q': 'C', '2K': 'D', '2A': 'E', '34': 'A', '35': 'A', '36': 'A', '37': 'A', '38': 'B', '39': 'B', '3T': 'C', '3J': 'C', '3Q': 'D', '3K': 'D', '3A': 'E', '45': 'B', '46': 'B', '47': 'B', '48': 'B', '49': 'B', '4T': 'C', '4J': 'C', '4Q': 'D', '4K': 'D', '4A': 'E', '56': 'B', '57': 'B', '58': 'B', '59': 'C', '5T': 'C', '5J': 'C', '5Q': 'D', '5K': 'E', '5A': 'F', '67': 'C', '68': 'C', '69': 'C', '6T': 'C', '6J': 'D', '6Q': 'D', '6K': 'E', '6A': 'E', '78': 'C', '79': 'C', '7T': 'D', '7J': 'D', '7Q': 'D', '7K': 'E', '7A': 'F', '89': 'D', '8T': 'D', '8J': 'D', '8Q': 'E', '8K': 'E', '8A': 'F', '9T': 'D', '9J': 'E', '9Q': 'E', '9K': 'E', '9A': 'F', 'TJ': 'E', 'TQ': 'E', 'TK': 'F', 'TA': 'F', 'JQ': 'E', 'JK': 'F', 'JA': 'G', 'QK': 'F', 'QA': 'G', 'KA': 'G', '2s3s': 'A', '2s4s': 'B', '2s5s': 'B', '2s6s': 'B', '2s7s': 'B', '2s8s': 'B', '2s9s': 'C', '2sTs': 'C', '2sJs': 'D', '2sQs': 'D', '2sKs': 'E', '2sAs': 'E', '3s4s': 'B', '3s5s': 'B', '3s6s': 'B', '3s7s': 'B', '3s8s': 'B', '3s9s': 'C', '3sTs': 'C', '3sJs': 'D', '3sQs': 'D', '3sKs': 'E', '3sAs': 'F', '4s5s': 'B', '4s6s': 'B', '4s7s': 'C', '4s8s': 'C', '4s9s': 'C', '4sTs': 'C', '4sJs': 'D', '4sQs': 'D', '4sKs': 'E', '4sAs': 'F', '5s6s': 'C', '5s7s': 'C', '5s8s': 'C', '5s9s': 'C', '5sTs': 'C', '5sJs': 'D', '5sQs': 'E', '5sKs': 'E', '5sAs': 'F', '6s7s': 'C', '6s8s': 'C', '6s9s': 'D', '6sTs': 'D', '6sJs': 'D', '6sQs': 'E', '6sKs': 'E', '6sAs': 'F', '7s8s': 'D', '7s9s': 'D', '7sTs': 'D', '7sJs': 'D', '7sQs': 'E', '7sKs': 'E', '7sAs': 'F', '8s9s': 'D', '8sTs': 'D', '8sJs': 'E', '8sQs': 'E', '8sKs': 'F', '8sAs': 'F', '9sTs': 'E', '9sJs': 'E', '9sQs': 'E', '9sKs': 'F', '9sAs': 'F', 'TsJs': 'E', 'TsQs': 'F', 'TsKs': 'F', 'TsAs': 'G', 'JsQs': 'F', 'JsKs': 'F', 'JsAs': 'G', 'QsKs': 'F', 'QsAs': 'G', 'KsAs': 'G'}

In [24]:
import ast

total_data = []
model = 'res_v3_b3'
for i in range(1):
    file_path = f'../assets/slumbot/record.txt'
    with open(file_path, "r") as file:
        for idx, line in enumerate(file):
            hand_data = {} 
            cols = line.split(",")
            hand_data['id'] = ast.literal_eval(cols[0][5:])
            hand_data['is_first'] = ast.literal_eval(cols[1][12:])
            hand_data['hand_win'] = ast.literal_eval(cols[2][12:])
            hand_data['total_win'] = ast.literal_eval(cols[3][13:])
            hand_data['history_action'] = cols[4][18:]
            hand_data['hole_cards'] = ast.literal_eval((','.join(cols[5:7]))[14:])
            hand_data['bot_hole_cards'] = ast.literal_eval((','.join(cols[7:9]))[18:])
            hand_data['board_cards'] = ast.literal_eval((','.join(cols[9:]))[15:])
            total_data.append(hand_data)
        file.close()
len(total_data)

16557

In [25]:
output_record = []
NUM_2_INDEX = {
    2: 0,
    5: 1,
    6: 2,
    7: 3,
}
output_record_path = f'../assets/slumbot/output_record.txt'
with open(output_record_path, "r") as file:
    data = file.readlines()
output_record = [ast.literal_eval(line.strip()) for line in data]
len(output_record)

16558

In [29]:
import re

def transform(cards, idx):
	num_dict = {
		"s": 0,
		"h": 0,
		"c": 0,
		"d": 0,
	}
	
	for card in cards:
		num_dict[card[-1]] += 1
	
	max_suit = max(num_dict, key=num_dict.get)
	max_suit_count = num_dict[max_suit]

	MIN_NUM = {2: 2, 5: 3, 6: 4, 7: 5}
	if max_suit_count < MIN_NUM[idx]:
		return ''.join([f"{card[:-1]}" for card in cards])
	else:
		result = []
		for card in cards:
			suit = card[-1]
			if suit == max_suit:
				result.append(f"{card[:-1]}s") 
			else:
				result.append(f"{card[:-1]}o") 
		return ''.join(result)

def find(code, idx):
	def get_card_rank(card):
		ranks = '23456789TJQKA'
		return ranks.index(card)
	
	perm = ""
	if len(code) == idx:
		hand = ''.join(sorted(code[:2], key=get_card_rank))
		remaining = ''.join(sorted(code[2:], key=get_card_rank))
		perm = hand + remaining

	elif len(code) == idx*2:
		grouped = [code[i:i+2] for i in range(0, len(code), 2)]
		hand = ''.join(sorted(grouped[:2], key=lambda x: (get_card_rank(x[0]), x[1] )))
		remaining = ''.join(sorted(grouped[2:], key=lambda x: (get_card_rank(x[0]), x[1]) ))
		perm = hand + remaining

	else:
		return None
	
	if perm in ref_data[idx]:
		return [perm, ref_data[idx][perm]]

	print(f"{code}, {perm} not found")
	
	return None

def get_curr_street_action(path, IDX, is_first, hand_win):
	splits = path.split('/')
	curr_splits = splits[-1]
	if curr_splits.endswith('f') and hand_win < 0:
		return 'f'
	elif curr_splits == 'f' and hand_win > 0:
		return '/'
	result = re.split(r'[kbfc]+', curr_splits) 
	matches = list(re.finditer(r'[kbfc]', curr_splits))	
	if len(matches) <= 0: 
		return ''
	action1 = matches[1].group()
	action2 = matches[0].group()
	return action1 if is_first else action2

IDX = 7
side = 'model' # or slumbot
cnts = [0 for i in range(8)]
my_data = [[] for i in range(8)]
for i, hand_data in enumerate(total_data):
	cards = []
	hand_win = 0
	if side == 'model':
		cards = hand_data['hole_cards'] + hand_data['board_cards']
		hand_win = hand_data['hand_win']
	elif side == 'slumbot':
		cards = hand_data['bot_hole_cards'] + hand_data['board_cards']
		hand_win = -hand_data['hand_win']
	# stats
	idx = len(cards)
	cnts[idx] += 1
	if idx >= IDX:
		cards = cards[:IDX]
		code = transform(cards, IDX)
		res = find(code, IDX)
		if res == None:
			continue
		group = res[-1]

		action = output_record[i][NUM_2_INDEX[IDX]][0] if len(output_record[i][NUM_2_INDEX[IDX]]) else '/'
		# action = get_curr_street_action(hand_data['history_action'], IDX, hand_data['is_first'], hand_win)
		if action == '/': continue
		
		my_data[IDX].append({
			'my_hole_cards': cards[:2],
			'slumbot_hole_cards': hand_data['bot_hole_cards'],
			'board_cards': hand_data['board_cards'],
			'hand_win': hand_win,
			'code': code,
			'group': group,
			'is_first': hand_data['is_first'],
			'action_path': hand_data['history_action'],
			'target_action_path': action,
		})
		
len(my_data[IDX])

2374

In [33]:
import pandas as pd

df = pd.DataFrame(my_data[IDX])
df

,my_hole_cards,slumbot_hole_cards,board_cards,hand_win,code,group,is_first,action_path,target_action_path
0,"[Jh, Ts]","[Ah, Tc]","[As, Jc, 5c, Qd, Ac]",-4600,JTAJ5QA,H,True,b500c/kb300c/kb200b1500b3000c/b800c,c
1,"[6d, 3d]","[Ad, Qc]","[6c, 5d, 2h, 2s, 4s]",1550,6365224,J,False,b200b400c/b250c/b700c/b200c,b0.5
2,"[8c, 4d]","[Kd, 4c]","[Kc, 9s, 8h, 4s, Ts]",-12100,84K984T,I,True,b200c/kb900c/kb300c/kb300b5350b10700c,b1.0
3,"[Qc, 8c]","[Kd, Tc]","[Jh, 9d, 8s, Kc, Jd]",-4800,Q8J98KJ,G,False,b200b400c/b200c/b250b2100b4200c/kk,k
4,"[7s, 5d]","[Qh, 9h]","[As, Ac, Tc, Td, Kc]",0,75AATTK,G,True,b900c/b100b200c/kb300c/kb200c,b0.5
...,...,...,...,...,...,...,...,...,...
2369,"[4h, 2d]","[Jd, 8d]","[Qc, 8s, 6c, 2h, Th]",-4500,42Q862T,E,True,b500c/kb200b1000b2000c/b500b1000c/kb1000c,b1.0
2370,"[5s, 2c]","[9h, 8c]","[Js, 7s, 4c, 9c, Ks]",1100,52J749K,A,True,b300c/kb500c/kb300c/kb500f,b2.0
2371,"[Qs, 9d]","[Ks, 9c]","[Qc, Jd, Th, Jh, As]",-1900,Q9QJTJA,G,True,b200c/kb200c/b400b900c/b300b600c,b0.5
2372,"[Jc, 5s]","[4s, 4h]","[6h, 2s, 2h, 6c, 9s]",1400,J562269,C,True,b200c/kb300c/kb900c/kb300f,b1.0
2373,"[9h, 4s]","[Ks, Jc]","[Jh, 8s, 6d, 5c, Qd]",-1300,94J865Q,B,True,b300c/kb300c/kb200c/kb500c,b2.0

In [34]:
pivot = pd.crosstab(df['target_action_path'], df['group'], normalize='columns') * 100

pivot = pivot.round(2)

all_actions = ['b0.5', 'b1.0', 'b2.0', 'b4.0', 'b8.0', 'b15.0', 'b25.0', 'b50.0', 'k', 'f', 'c']
missing_actions = [action for action in all_actions if action not in pivot.index]
for action in missing_actions:
    pivot.loc[action] = 0.0

pivot = pivot.reindex(all_actions)
pivot.loc['b_total'] = pivot.loc[['b0.5', 'b1.0', 'b2.0', 'b4.0', 'b8.0', 'b15.0', 'b25.0', 'b50.0']].sum()
pivot.loc['b_low'] = pivot.loc[['b0.5', 'b1.0', 'b2.0']].sum()
pivot.loc['b_high'] = pivot.loc[['b4.0', 'b8.0', 'b15.0', 'b25.0', 'b50.0']].sum()
pivot

group,A,B,C,D,E,F,G,H,I,J
target_action_path,,,,,,,,,,
b0.5,34.90,32.34,34.19,33.48,35.56,32.69,31.09,33.33,32.50,31.66
b1.0,18.23,20.40,16.24,21.46,20.00,20.19,20.22,20.39,19.58,20.06
b2.0,12.50,13.43,13.25,14.16,13.78,12.02,13.86,12.16,12.08,13.17
b4.0,5.73,1.49,5.13,5.58,4.00,4.33,3.75,4.71,5.00,3.13
b8.0,0.00,0.00,1.28,1.72,0.00,0.48,0.00,0.39,0.42,0.31
b15.0,0.00,0.50,0.43,0.43,0.00,0.00,0.00,0.00,0.00,0.00
b25.0,0.52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
b50.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
k,26.56,28.86,28.21,21.89,25.78,27.40,29.21,25.88,26.25,28.53
f,1.04,0.50,0.43,0.43,0.00,0.96,0.75,0.78,0.42,0.94
c,0.52,2.49,0.85,0.86,0.89,1.92,1.12,2.35,3.75,2.19
b_total,71.88,68.16,70.52,76.83,73.34,69.71,68.92,70.98,69.58,68.33
b_low,65.63,66.17,63.68,69.10,69.34,64.90,65.17,65.88,64.16,64.89
b_high,6.25,1.99,6.84,7.73,4.00,4.81,3.75,5.10,5.42,3.44

In [32]:
pivot.to_csv(f'../assets/slumbot/stat/stat-8/{model}-{side}-{IDX}.csv')

In [33]:
import pandas as pd
import os
from pathlib import Path

def combine_csv_to_excel(folder_path, output_excel='combined_data.xlsx'):
    if not os.path.exists(folder_path):
        raise ValueError(f"{folder_path} not exist")
    
    csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
    
    if not csv_files:
        print("no csv!")
        return
    
    with pd.ExcelWriter(output_excel) as writer:
        for csv_file in csv_files:
            try:
                file_path = os.path.join(folder_path, csv_file)
                df = pd.read_csv(file_path)
                
                sheet_name = Path(csv_file).stem
                
                if len(sheet_name) > 31:
                    sheet_name = sheet_name[:31]
                
                df.to_excel(writer, sheet_name=sheet_name, index=False)
                print(f"handled: {csv_file}")
                
            except Exception as e:
                print(f"error while handling {csv_file}: {str(e)}")
    
folder_path = "../assets/slumbot/stat/stat-8"
output_path = "../assets/slumbot/stat/stat-8/stat-res-v3-b3.xlsx"
combine_csv_to_excel(folder_path, output_path)

handled: res_v3_b3-model-2.csv
handled: res_v3_b3-model-5.csv
handled: res_v3_b3-model-6.csv
handled: res_v3_b3-model-7.csv